services:
  dev:
    build:
      context: .
      target: dev
    container_name: kartj-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  prod:
    build:
      context: .
      target: runner
    container_name: kartj-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
